global:
  resolve_timeout: 2m
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: '5eaixAxi4lQjhlNmoIqFar--VjF4WAPZds3ox0Isn2A'
  wechat_api_corp_id: 'ww2eb05aad72a447e0'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'wechat'

receivers:
- name: 'wechat'
  wechat_configs:
    - send_resolved: true
      to_party: '1'
      agent_id: '1000002'