version: "3"

services:
  prometheus:
    image: bitnami/prometheus
    volumes:
      - "./prometheus/prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml"
      - "./prometheus/mysqld_rules.yaml:/opt/bitnami/prometheus/conf/mysqld_rules.yaml"
      - "prometheus_data:/opt/bitnami/prometheus/data"
    ports:
      - "10000:9090"
  
  alertmanager:
    image: bitnami/alertmanager
    volumes:
      - "./alertmanager/alertmanager.yaml:/opt/bitnami/alertmanager/conf/config.yml"
    ports:
      - "10001:9093"
  
  grafana:
    image: bitnami/grafana
    volumes:
      - "grafana_data:/opt/bitnami/grafana/data"
    ports:
      - "10002:3000"
  
  mysqld_exporter:
    image: bitnami/mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:Qweasd123@(192.168.251.60:3306)/

volumes:
  prometheus_data:
  grafana_data: